### ISSUE TITLE
Not sure if Bug??

### ISSUE THREAD

**Issue by 4r33d0m** [capt-meelo/Beaconator#6]
null value error at beaconator.cna:243

Tried with x86 and x64 using PEZor.  With and without Syscalls in case that made any difference.

Line 243 reads:

closef($process);

**Comment by capt-meelo** [comment]
have you added PEzor's `$PATH` variable in your `~/.profile` or `~/.bashrc` (if you're using Bash), OR `~/.zprofile` or `~/.zshrc` (if you're using ZSH)?
